kumuluzee:
  name: delivery-time-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
#  datasources:
#    - jndi-name: jdbc/DeliveryMetadataDS
#      connection-url: jdbc:postgresql://localhost:5432/delivery-metadata
#      username: dbuser
#      password: postgres
#      max-pool-size: 20
  health:
#    checks:
#      data-source-health-check:
#        jndi-name: jdbc/DeliveryMetadataDS
#        type: liveness
    metrics:
        web-instrumentation:
          - name: deliveries-endpoint
            url-pattern: /v1/deliveryTime/*
    logs:
      config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="comments">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="a7f2e87e-7284-4b21-8eca-3dfbe318dc71-ls.logit.io"
                                      port="20918" protocol="udp">
                                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info" />
                                          <AppenderRef ref="logstash" level="trace" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'

rest-properties:
  maintenance-mode: false
  broken: false

app-properties:
  delivery-time-client:
    geocoder-key: be886d430eead1e57fd5c3db1f805ded
    rapidapi-key: 197be5d856mshf891aa29c50ec04p1d3d61jsna8cb6a927b9b

#kumuluzee.name
#KUMULUEE_NAME

#kumuluzee.env.name
#KUMULUZEE_ENV_NAME

#kumuluzee.datasources[0].connection-url
#KUMULZEE_DATASOURCES0_CONNECTIONURL